services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user 
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27020:27017"
    networks:
      - examenparcial2_mongo-network

  calculadora:
    image: ghcr.io/dinocodeadvisor/web-3/examen-p2-backend:sha-4e96eef
    pull_policy: always
    ports:
      - "8089:8000"
    volumes:
      - ./backend:/app
    networks:
      - examenparcial2_mongo-network

  frontend:
    image: ghcr.io/dinocodeadvisor/web-3/examen-p2-frontend:sha-a04eb9e
    pull_policy: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - calculadora
    networks:
      - examenparcial2_mongo-network

networks:
  examenparcial2_mongo-network:
    driver: bridge
